name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: ["opened", "synchronize", "reopened"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - run: deno fmt --check
      - run: deno lint

      - run: deno test --coverage=tmp/cov/ --junit-path=tmp/junit.xml
      - run: deno coverage --lcov tmp/cov/ > tmp/cov.lcov

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: tmp/junit.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: tmp/cov.lcov
